import Head from 'next/head'
import NavBar from "./components/NavBar"


export default function Casa() {
    return (
        <div>
            <Head>
                <title>User Pages</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
            </Head>
            <NavBar title={'User'}/>
            <h1>CAsa</h1>
        </div>
    )
}
